/* tslint:disable */
export interface DirectoryVO {
  address?: string;
  autoserviceCompetence?: string;
  catalog?: string;
  chainPharmacyCompetence?: string;
  conceptType?: string;
  consultingRoom?: string;
  director?: string;
  district?: string;
  email?: string;
  format?: string;
  healthInstitution?: string;
  hub?: string;
  location?: string;
  newElement?: boolean;
  opening?: string;
  openingDate?: string;
  pharmacy?: string;
  prototype?: string;
  region?: string;
  spoke?: string;
  state?: string;
  status?: string;
  storeInCombo?: string;
  storeNumber?: string;
  storeOfCombo?: string;
  storeTrouble?: string;
  stores?: string;
  subDirector?: string;
  supervisor?: string;
  supervisorZone?: string;
  trouble?: string;
  unit?: string;
  upcCat27?: string;
  upcCat40?: string;
  vendorConsultingRoom?: string;
  zone?: string;
}
